
version: '3.7'

services:
  bluesky:
    image: bluesky:latest
    volumes:
      - ./bluesky:/usr/src/app
    expose:
      - 9000
      - 9001
  bluebird:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5001
    environment:
      - BS_HOST=bluesky
