
version: '3.7'

services:
  bluesky:
    image: turinginst/bluesky:1.0.3
    volumes:
      - ./bluesky:/usr/src/app
    expose:
      - 9000
      - 9001
# Uncomment to also publish the BlueSky ports externally
#    ports:
#      - 9000:9000
#      - 9001:9001
  bluebird:
    build: .
    volumes:
      - .:/usr/src/app
      - ./docker_logs:/usr/src/app/logs
    ports:
      - 5001:5001
    environment:
      - BS_HOST=bluesky
